"""
MCP Tool Definitions for Outlook Graph Mail Server - AUTO-GENERATED FILE
DO NOT EDIT THIS FILE MANUALLY!

This file is automatically generated when you save changes in the MCP Tool Editor.
It contains clean tool definitions for use with Claude/OpenAI APIs.
Internal metadata fields (mcp_service, mcp_service_factors) are removed.

Generated from: MCP Tool Editor Web Interface
To modify: Use the web editor at http://localhost:8091
"""

from typing import List, Dict, Any

# MCP Tool Definitions
MCP_TOOLS: List[Dict[str, Any]] = [
    {
        "name": "query_emails",
        "description": "Query and filter emails with advanced options",
        "inputSchema": {
            "type": "object",
            "properties": {
                "user_email": {
                    "type": "string",
                    "description": "User email address"
                },
                "filter": {
                    "type": "object",
                    "description": "Filter parameters for querying emails",
                    "properties": {
                        "from": {
                            "type": "string",
                            "description": "Filter by sender email"
                        },
                        "subject": {
                            "type": "string",
                            "description": "Filter by subject"
                        },
                        "body": {
                            "type": "string",
                            "description": "Filter by body content"
                        },
                        "has_attachments": {
                            "type": "boolean",
                            "description": "Filter emails with attachments"
                        },
                        "is_read": {
                            "type": "boolean",
                            "description": "Filter by read status"
                        },
                        "importance": {
                            "type": "string",
                            "enum": [
                                "low",
                                "normal",
                                "high"
                            ],
                            "description": "Filter by importance"
                        },
                        "received_after": {
                            "type": "string",
                            "format": "date-time",
                            "description": "Filter emails received after this date"
                        },
                        "received_before": {
                            "type": "string",
                            "format": "date-time",
                            "description": "Filter emails received before this date"
                        }
                    }
                },
                "exclude": {
                    "type": "object",
                    "description": "Exclude parameters for filtering",
                    "properties": {
                        "from": {
                            "type": "string",
                            "description": "Exclude sender email"
                        },
                        "subject": {
                            "type": "string",
                            "description": "Exclude by subject"
                        },
                        "body": {
                            "type": "string",
                            "description": "Exclude by body content"
                        }
                    }
                },
                "select": {
                    "type": "object",
                    "description": "Select specific fields to return",
                    "properties": {
                        "fields": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "description": "List of fields to return"
                        }
                    }
                },
                "top": {
                    "type": "integer",
                    "description": "Maximum number of emails to return (default: 10)"
                },
                "orderby": {
                    "type": "string",
                    "description": "Sort order (default: 'receivedDateTime desc')"
                }
            },
            "required": [
                "user_email"
            ]
        }
    }
]


def get_tool_by_name(tool_name: str) -> Dict[str, Any] | None:
    """Get a specific tool definition by name"""
    for tool in MCP_TOOLS:
        if tool["name"] == tool_name:
            return tool
    return None


def get_tool_names() -> List[str]:
    """Get list of all available tool names"""
    return [tool["name"] for tool in MCP_TOOLS]
