"""
MCP Tool Definitions for Outlook Graph Mail Server - AUTO-GENERATED FILE
DO NOT EDIT THIS FILE MANUALLY!

This file is automatically generated when you save changes in the MCP Tool Editor.
It contains clean tool definitions for use with Claude/OpenAI APIs.
Internal metadata fields (mcp_service, mcp_service_factors) are removed.

Generated from: MCP Tool Editor Web Interface
To modify: Use the web editor at http://localhost:8091
"""

from typing import List, Dict, Any

# MCP Tool Definitions
MCP_TOOLS: List[Dict[str, Any]] = [
    {
        "name": "get_email_handler",
        "description": "Get a specific email by ID",
        "inputSchema": {
            "properties": {
                "message_id": {
                    "description": "Message ID",
                    "type": "string"
                },
                "user_email": {
                    "description": "User email address",
                    "type": "string"
                }
            },
            "required": [
                "user_email",
                "message_id"
            ],
            "type": "object"
        }
    },
    {
        "name": "test_handler",
        "description": "New tool description",
        "inputSchema": {
            "type": "object",
            "properties": {
                "example_param": {
                    "type": "string",
                    "description": "Example parameter"
                },
                "from_address": {
                    "type": "string",
                    "description": "from/emailAddress/address - 단일 또는 여러 발신자 이메일 주소"
                },
                "sender_address": {
                    "type": "string",
                    "description": "sender/emailAddress/address - 실제 발신자 이메일 주소"
                },
                "exclude_from_address": {
                    "type": "string",
                    "description": "제외할 발신자 주소 (from 필드)"
                }
            },
            "required": []
        }
    }
]


def get_tool_by_name(tool_name: str) -> Dict[str, Any] | None:
    """Get a specific tool definition by name"""
    for tool in MCP_TOOLS:
        if tool["name"] == tool_name:
            return tool
    return None


def get_tool_names() -> List[str]:
    """Get list of all available tool names"""
    return [tool["name"] for tool in MCP_TOOLS]
