"""
MCP Tool Definitions for Outlook Graph Mail Server - AUTO-GENERATED FILE
DO NOT EDIT THIS FILE MANUALLY!

This file is automatically generated when you save changes in the MCP Tool Editor.
It contains clean tool definitions for use with Claude/OpenAI APIs.
Internal metadata fields (mcp_service, mcp_service_factors) are removed.

Generated from: MCP Tool Editor Web Interface
To modify: Use the web editor at http://localhost:8091
"""

from typing import List, Dict, Any

# MCP Tool Definitions
MCP_TOOLS: List[Dict[str, Any]] = [
    {
        "name": "query_emails",
        "description": "Query and filter emails with advanced options",
        "inputSchema": {
            "properties": {
                "exclude": {
                    "description": "Exclude parameters for filtering",
                    "properties": {
                        "body": {
                            "description": "Exclude by body content",
                            "type": "string"
                        },
                        "from": {
                            "description": "Exclude sender email",
                            "type": "string"
                        },
                        "subject": {
                            "description": "Exclude by subject",
                            "type": "string"
                        }
                    },
                    "type": "object"
                },
                "filter": {
                    "description": "Filter parameters for querying emails",
                    "properties": {
                        "body": {
                            "description": "Filter by body content",
                            "type": "string"
                        },
                        "from": {
                            "description": "Filter by sender email",
                            "type": "string"
                        },
                        "has_attachments": {
                            "description": "Filter emails with attachments",
                            "type": "boolean"
                        },
                        "importance": {
                            "description": "Filter by importance",
                            "enum": [
                                "low",
                                "normal",
                                "high"
                            ],
                            "type": "string"
                        },
                        "is_read": {
                            "description": "Filter by read status",
                            "type": "boolean"
                        },
                        "received_after": {
                            "description": "Filter emails received after this date",
                            "format": "date-time",
                            "type": "string"
                        },
                        "received_before": {
                            "description": "Filter emails received before this date",
                            "format": "date-time",
                            "type": "string"
                        },
                        "subject": {
                            "description": "Filter by subject",
                            "type": "string"
                        }
                    },
                    "type": "object"
                },
                "orderby": {
                    "description": "Sort order (default: 'receivedDateTime desc')",
                    "type": "string"
                },
                "select": {
                    "description": "Select specific fields to return",
                    "properties": {
                        "fields": {
                            "description": "List of fields to return",
                            "items": {
                                "type": "string"
                            },
                            "type": "array"
                        }
                    },
                    "type": "object"
                },
                "top": {
                    "description": "Maximum number of emails to return (default: 10)",
                    "type": "integer"
                },
                "user_email": {
                    "description": "User email address",
                    "type": "string"
                }
            },
            "required": [
                "user_email"
            ],
            "type": "object"
        }
    },
    {
        "name": "new_tool_1765716071106",
        "description": "New tool description",
        "inputSchema": {
            "type": "object",
            "properties": {
                "example_param": {
                    "type": "string",
                    "description": "Example parameter"
                },
                "from_address": {
                    "type": "string",
                    "description": "from/emailAddress/address - 단일 또는 여러 발신자 이메일 주소"
                },
                "sender_address": {
                    "type": "string",
                    "description": "sender/emailAddress/address - 실제 발신자 이메일 주소"
                },
                "received_date_time": {
                    "type": "string",
                    "description": "메일 수신 날짜/시간 - 이 시간 이후 메일만 조회 (ISO 8601 형식)"
                }
            },
            "required": [
                "from_address"
            ]
        },
        "mcp_service_signature": "async query_filter(user_email: str, filter: FilterParams, exclude: Optional[ExcludeParams], select: Optional[SelectParams], client_filter: Optional[ExcludeParams], top: int = 450, orderby: Optional[str])"
    }
]


def get_tool_by_name(tool_name: str) -> Dict[str, Any] | None:
    """Get a specific tool definition by name"""
    for tool in MCP_TOOLS:
        if tool["name"] == tool_name:
            return tool
    return None


def get_tool_names() -> List[str]:
    """Get list of all available tool names"""
    return [tool["name"] for tool in MCP_TOOLS]
