"""
MCP Tool Definition Templates - AUTO-GENERATED FILE
DO NOT EDIT THIS FILE MANUALLY!

This file is automatically generated when you save changes in the MCP Tool Editor.
It contains the full tool definitions including internal metadata fields:
- mcp_service: Object containing:
  - name: The handler function name
  - signature: The function parameters from the @mcp_service decorator
- mcp_service_factors: Internal routing and parameter mapping information

Generated from: MCP Tool Editor Web Interface
To modify: Use the web editor at http://localhost:8091
"""

from typing import List, Dict, Any

# MCP Tool Templates with service field and service factors
MCP_TOOLS: List[Dict[str, Any]] = [
    {
        "name": "query_emails",
        "description": "Query and filter emails with advanced options",
        "inputSchema": {
            "type": "object",
            "properties": {
                "exclude": {
                    "type": "object",
                    "description": "Exclude parameters for filtering",
                    "properties": {
                        "body": {
                            "type": "string",
                            "description": "Exclude by body content"
                        },
                        "from": {
                            "type": "string",
                            "description": "Exclude sender email"
                        },
                        "subject": {
                            "type": "string",
                            "description": "Exclude by subject"
                        }
                    }
                },
                "filter": {
                    "type": "object",
                    "description": "Filter parameters for querying emails",
                    "properties": {
                        "body": {
                            "type": "string",
                            "description": "Filter by body content"
                        },
                        "from": {
                            "type": "string",
                            "description": "Filter by sender email"
                        },
                        "has_attachments": {
                            "type": "boolean",
                            "description": "Filter emails with attachments"
                        },
                        "importance": {
                            "type": "string",
                            "description": "Filter by importance",
                            "enum": [
                                "low",
                                "normal",
                                "high"
                            ]
                        },
                        "is_read": {
                            "type": "boolean",
                            "description": "Filter by read status"
                        },
                        "received_after": {
                            "type": "string",
                            "description": "Filter emails received after this date",
                            "format": "date-time"
                        },
                        "received_before": {
                            "type": "string",
                            "description": "Filter emails received before this date",
                            "format": "date-time"
                        },
                        "subject": {
                            "type": "string",
                            "description": "Filter by subject"
                        }
                    }
                },
                "orderby": {
                    "type": "string",
                    "description": "Sort order (default: 'receivedDateTime desc')"
                },
                "select": {
                    "type": "object",
                    "description": "Select specific fields to return",
                    "properties": {
                        "fields": {
                            "type": "array",
                            "description": "List of fields to return",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                },
                "top": {
                    "type": "integer",
                    "description": "Maximum number of emails to return (default: 10)"
                },
                "user_email": {
                    "type": "string",
                    "description": "User email address"
                }
            },
            "required": [
                "user_email"
            ]
        }
    },
    {
        "name": "new_tool_1765718733273",
        "description": "New tool description",
        "inputSchema": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "object",
                    "description": "FilterParams parameters",
                    "properties": {
                        "from_address": {
                            "type": "string",
                            "description": "from/emailAddress/address - 단일 또는 여러 발신자 이메일 주소"
                        },
                        "sender_address": {
                            "type": "string",
                            "description": "sender/emailAddress/address - 실제 발신자 이메일 주소"
                        }
                    },
                    "required": [],
                    "baseModel": "FilterParams"
                }
            },
            "required": []
        },
        "mcp_service": {
            "name": "query_filter",
            "signature": "user_email: str, filter: FilterParams, exclude: Optional[ExcludeParams], select: Optional[SelectParams], client_filter: Optional[ExcludeParams], top: int = 450, orderby: Optional[str]"
        }
    }
]