#!/usr/bin/env python3
"""
Generate tool_editor_web_server_mappings.py from @mcp_service decorators

This script scans the codebase for @mcp_service decorators, extracts server_name values,
and generates a simple mapping module that can be imported by tool_editor_web.py
"""

import ast
import os
from pathlib import Path
from typing import Set


def extract_server_name_from_file(file_path: str) -> Set[str]:
    """Extract all server_name values from @mcp_service decorators in a Python file"""
    server_names = set()

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()

        tree = ast.parse(content)

        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                # Check if function has @mcp_service decorator
                for decorator in node.decorator_list:
                    decorator_name = None

                    # Handle simple decorator: @mcp_service
                    if isinstance(decorator, ast.Name):
                        decorator_name = decorator.id
                    # Handle decorator with args: @mcp_service(...)
                    elif isinstance(decorator, ast.Call):
                        if isinstance(decorator.func, ast.Name):
                            decorator_name = decorator.func.id

                    if decorator_name == 'mcp_service':
                        # Extract server_name from decorator arguments
                        if isinstance(decorator, ast.Call):
                            for keyword in decorator.keywords:
                                if keyword.arg == 'server_name' and isinstance(keyword.value, ast.Constant):
                                    server_name = keyword.value.value
                                    if server_name:
                                        server_names.add(server_name)
                                        print(f"  Found server_name='{server_name}' in {file_path}")

    except Exception as e:
        print(f"Error processing {file_path}: {e}")

    return server_names


def scan_codebase_for_servers(base_dir: str) -> Set[str]:
    """Scan entire codebase for @mcp_service decorators and extract server names"""
    all_server_names = set()

    print(f"Scanning codebase in: {base_dir}")

    for py_file in Path(base_dir).rglob("*.py"):
        # Skip venv, __pycache__, and other non-source directories
        if any(part in str(py_file) for part in ['venv', '__pycache__', '.git', 'node_modules', 'backups']):
            continue

        server_names = extract_server_name_from_file(str(py_file))
        all_server_names.update(server_names)

    return all_server_names


def generate_server_mappings(server_names: Set[str], output_path: str):
    """
    Generate tool_editor_web_server_mappings.py module

    Args:
        server_names: Set of server names discovered from @mcp_service decorators
        output_path: Path where the mapping file will be saved
    """
    print(f"\nGenerating server mappings for {len(server_names)} server(s):")
    for server_name in sorted(server_names):
        print(f"  - {server_name}")

    # Default server is the first one alphabetically
    default_server = sorted(server_names)[0] if server_names else 'outlook'

    # Generate Python code
    content = f'''"""
Server name mappings - AUTO-GENERATED FILE
DO NOT EDIT THIS FILE MANUALLY!

This file is automatically generated from @mcp_service decorators.
To regenerate: python ../jinja/generate_server_mappings.py
"""

# List of all known server names
SERVER_NAMES = [
{chr(10).join(f"    '{name}'," for name in sorted(server_names))}
]

# Default server name
DEFAULT_SERVER = '{default_server}'


def get_server_name_from_profile(profile: str) -> str | None:
    """
    Determine server name from profile string

    Args:
        profile: Profile name or identifier

    Returns:
        Server name or None if not found
    """
    if profile == '_default':
        return DEFAULT_SERVER

    # Check if profile contains any known server name
    for server_name in SERVER_NAMES:
        if server_name in profile:
            return server_name

    return None


def get_server_name_from_path(path: str) -> str | None:
    """
    Determine server name from file path

    Args:
        path: File path to analyze

    Returns:
        Server name or None if not found
    """
    # Check each known server name
    for server_name in SERVER_NAMES:
        # Check for various naming patterns
        patterns = [
            f'mcp_{{server_name}}',
            f'{{server_name}}_mcp',
            f'mcp{{server_name}}',
        ]
        for pattern in patterns:
            if pattern in path:
                return server_name

    return None
'''

    # Write the file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"\n✓ Generated {output_path}")
    print(f"  Server names: {', '.join(sorted(server_names))}")
    print(f"  Default server: {default_server}")


def main():
    """Main entry point"""
    # Determine project root (parent of jinja directory)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)

    print("=" * 60)
    print("Generate server mappings from @mcp_service decorators")
    print("=" * 60)
    print()

    # Scan codebase for server names
    server_names = scan_codebase_for_servers(project_root)

    if not server_names:
        print("\n⚠ No server_name values found in @mcp_service decorators")
        print("  Creating default with 'outlook' server")
        server_names = {"outlook"}

    print(f"\nDiscovered {len(server_names)} unique server name(s):")
    for name in sorted(server_names):
        print(f"  - {name}")

    # Generate server mappings in mcp_editor directory
    output_path = os.path.join(project_root, "mcp_editor", "tool_editor_web_server_mappings.py")

    # Backup existing file if it exists
    if os.path.exists(output_path):
        import shutil
        from datetime import datetime
        backup_dir = os.path.join(project_root, "mcp_editor", "backups")
        os.makedirs(backup_dir, exist_ok=True)
        backup_filename = f"tool_editor_web_server_mappings_{datetime.now().strftime('%Y%m%d_%H%M%S')}.py"
        backup_path = os.path.join(backup_dir, backup_filename)
        shutil.copy2(output_path, backup_path)
        print(f"\n📦 Backed up existing file to: backups/{backup_filename}")

    # Generate new mapping file
    generate_server_mappings(server_names, output_path)

    print("\n" + "=" * 60)
    print("✓ Done!")
    print("=" * 60)
    print()
    print("Next steps:")
    print("  1. Review the generated mapping file")
    print("  2. The tool_editor_web.py will automatically use these mappings")
    print("  3. Restart the web editor if it's running")


if __name__ == "__main__":
    main()
