"""
MCP Tool Definitions for Outlook Server - AUTO-GENERATED FILE
DO NOT EDIT THIS FILE MANUALLY!

Generated from @mcp_service decorated functions in source code.
To regenerate: python mcp_editor/regenerate_tools.py outlook
"""

from typing import List, Dict, Any

# MCP Tool Definitions
MCP_TOOLS: List[Dict[str, Any]] = [
    {
        "name": "handle_query_filter",
        "description": "Build Microsoft Graph API query URL for email operations",
        "inputSchema": {
            "type": "object",
            "properties": {
                "user_email": {
                    "type": "string"
                },
                "filter": {
                    "type": "string"
                },
                "exclude": {
                    "type": "string"
                },
                "select": {
                    "type": "string"
                },
                "client_filter": {
                    "type": "string"
                },
                "top": {
                    "type": "integer"
                },
                "orderby": {
                    "type": "string"
                }
            },
            "required": [
                "user_email",
                "filter"
            ]
        }
    },
    {
        "name": "handle_query_search",
        "description": "Build Microsoft Graph API query URL for email operations",
        "inputSchema": {
            "type": "object",
            "properties": {
                "user_email": {
                    "type": "string"
                },
                "search": {
                    "type": "string"
                },
                "client_filter": {
                    "type": "string"
                },
                "select": {
                    "type": "string"
                },
                "top": {
                    "type": "integer"
                },
                "orderby": {
                    "type": "string"
                }
            },
            "required": [
                "user_email",
                "search"
            ]
        }
    },
    {
        "name": "handle_query_url",
        "description": "Build Microsoft Graph API query URL for email operations",
        "inputSchema": {
            "type": "object",
            "properties": {
                "user_email": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "top": {
                    "type": "integer"
                },
                "client_filter": {
                    "type": "string"
                }
            },
            "required": [
                "user_email",
                "url"
            ]
        }
    }
]


def get_tool_by_name(tool_name: str) -> Dict[str, Any] | None:
    """Get a specific tool definition by name"""
    for tool in MCP_TOOLS:
        if tool["name"] == tool_name:
            return tool
    return None


def get_tool_names() -> List[str]:
    """Get list of all available tool names"""
    return [tool["name"] for tool in MCP_TOOLS]
