"""
MCP Tool Definitions for Outlook Server - AUTO-GENERATED FILE
DO NOT EDIT THIS FILE MANUALLY!

This file is automatically generated when you save changes in the MCP Tool Editor.
It contains clean tool definitions for use with Claude/OpenAI APIs.
Internal metadata fields (mcp_service, mcp_service_factors) are removed.

Generated from: MCP Tool Editor Web Interface
To modify: Use the web editor at http://localhost:8091
"""

from typing import List, Dict, Any
import json

# MCP Tool Definitions
MCP_TOOLS: List[Dict[str, Any]] = json.loads("""
[
    {
        "name": "handler_mail_fetch_filter",
        "description": "필터 방식 메일 조회 기능",
        "inputSchema": {
            "type": "object",
            "properties": {
                "exclude_params": {
                    "type": "object",
                    "description": "제외 조건",
                    "baseModel": "ExcludeParams"
                },
                "filter_params": {
                    "type": "object",
                    "description": "메일 필터링 조건",
                    "properties": {
                        "received_date_from": {
                            "type": "string",
                            "description": "메일 수신 시작 날짜 (포함, receivedDateTime >= 이 값)"
                        },
                        "received_date_to": {
                            "type": "string",
                            "description": "메일 수신 종료 날짜 (포함, receivedDateTime <= 이 값)"
                        },
                        "sent_date_from": {
                            "type": "string",
                            "description": "메일 발신 시작 날짜 (포함, sentDateTime >= 이 값)"
                        },
                        "sent_date_to": {
                            "type": "string",
                            "description": "메일 발신 종료 날짜 (포함, sentDateTime <= 이 값)"
                        }
                    },
                    "baseModel": "FilterParams"
                }
            },
            "required": []
        }
    },
    {
        "name": "handler_mail_fetch_search",
        "description": "검색 방식 메일 조회 기능",
        "inputSchema": {
            "type": "object",
            "properties": {
                "search_term": {
                    "type": "string",
                    "description": "검색어 ($search 파라미터)"
                },
                "select_params": {
                    "type": "object",
                    "description": "조회할 필드 선택",
                    "properties": {
                        "fields": {
                            "type": "array",
                            "description": "조회할 필드 목록",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "baseModel": "SelectParams"
                },
                "top": {
                    "type": "integer",
                    "description": "반환할 최대 메일 수"
                }
            },
            "required": [
                "search_term"
            ]
        }
    },
    {
        "name": "handler_mail_process_with_download",
        "description": "첨부파일 다운로드 포함 메일 처리 기능",
        "inputSchema": {
            "type": "object",
            "properties": {
                "filter_params": {
                    "type": "object",
                    "description": "메일 필터링 조건",
                    "properties": {
                        "received_date_from": {
                            "type": "string",
                            "description": "메일 수신 시작 날짜"
                        },
                        "received_date_to": {
                            "type": "string",
                            "description": "메일 수신 종료 날짜"
                        }
                    },
                    "baseModel": "FilterParams"
                },
                "save_directory": {
                    "type": "string",
                    "description": "첨부파일 저장 디렉토리 경로"
                },
                "search_term": {
                    "type": "string",
                    "description": "검색어 (지정시 검색 모드로 전환)"
                },
                "top": {
                    "type": "integer",
                    "description": "반환할 최대 메일 수"
                }
            },
            "required": []
        }
    }
]
""")




def get_tool_by_name(tool_name: str) -> Dict[str, Any] | None:
    """Get a specific tool definition by name"""
    for tool in MCP_TOOLS:
        if tool["name"] == tool_name:
            return tool
    return None


def get_tool_names() -> List[str]:
    """Get list of all available tool names"""
    return [tool["name"] for tool in MCP_TOOLS]
