"""
MCP Tool Definitions for Outlook Server - AUTO-GENERATED FILE
DO NOT EDIT THIS FILE MANUALLY!

This file is automatically generated when you save changes in the MCP Tool Editor.
It contains clean tool definitions for use with Claude/OpenAI APIs.
Internal metadata fields (mcp_service, mcp_service_factors) are removed.

Generated from: MCP Tool Editor Web Interface
To modify: Use the web editor at http://localhost:8091
"""

from typing import List, Dict, Any
import json

# MCP Tool Definitions
MCP_TOOLS: List[Dict[str, Any]] = json.loads("""
[
    {
        "name": "mail_fetch_filter",
        "description": "필터 방식 메일 조회 기능",
        "inputSchema": {
            "type": "object",
            "properties": {
                "exclude_params": {
                    "type": "object",
                    "description": "제외 조건",
                    "baseModel": "ExcludeParams",
                    "targetParam": "exclude_params"
                },
                "filter_params": {
                    "type": "object",
                    "description": "메일 필터링 조건",
                    "properties": {
                        "received_date_from": {
                            "type": "string",
                            "description": "메일 수신 시작 날짜 (포함, receivedDateTime >= 이 값)"
                        },
                        "received_date_to": {
                            "type": "string",
                            "description": "메일 수신 종료 날짜 (포함, receivedDateTime <= 이 값)"
                        },
                        "sent_date_from": {
                            "type": "string",
                            "description": "메일 발신 시작 날짜 (포함, sentDateTime >= 이 값)"
                        },
                        "sent_date_to": {
                            "type": "string",
                            "description": "메일 발신 종료 날짜 (포함, sentDateTime <= 이 값)"
                        }
                    },
                    "baseModel": "FilterParams",
                    "targetParam": "filter_params"
                },
                "user_email": {
                    "type": "string",
                    "description": ""
                }
            },
            "required": []
        }
    },
    {
        "name": "mail_fetch_search",
        "description": "검색 방식 메일 조회 기능",
        "inputSchema": {
            "type": "object",
            "properties": {
                "search_term": {
                    "type": "string",
                    "description": "검색어 ($search 파라미터)"
                },
                "select_params": {
                    "type": "object",
                    "description": "조회할 필드 선택",
                    "properties": {
                        "fields": {
                            "type": "array",
                            "description": "조회할 필드 목록",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "baseModel": "SelectParams"
                },
                "top": {
                    "type": "integer",
                    "description": "반환할 최대 메일 수"
                },
                "user_email": {
                    "type": "string",
                    "description": ""
                }
            },
            "required": [
                "search_term"
            ]
        }
    },
    {
        "name": "mail_process_with_download",
        "description": "첨부파일 다운로드 포함 메일 처리 기능",
        "inputSchema": {
            "type": "object",
            "properties": {
                "filter_params": {
                    "type": "object",
                    "description": "메일 필터링 조건",
                    "properties": {
                        "received_date_from": {
                            "type": "string",
                            "description": "메일 수신 시작 날짜"
                        },
                        "received_date_to": {
                            "type": "string",
                            "description": "메일 수신 종료 날짜"
                        }
                    },
                    "baseModel": "FilterParams"
                },
                "save_directory": {
                    "type": "string",
                    "description": "첨부파일 저장 디렉토리 경로"
                },
                "search_term": {
                    "type": "string",
                    "description": "검색어 (지정시 검색 모드로 전환)"
                },
                "top": {
                    "type": "integer",
                    "description": "반환할 최대 메일 수"
                }
            },
            "required": []
        }
    },
    {
        "name": "mail_list_preview",
        "description": "특정 기간 동안 메일조회하고 body를 제외하고 대략적인 내용만 추출할 수 있는 데이터만 수신하여 테이블로 정리하는 도구 입니다.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "DatePeriodFilter": {
                    "type": "object",
                    "description": "에이전트는 는 사용자의 질의에 따라 검색 범위의 날짜를 추출한다.",
                    "properties": {
                        "received_date_from": {
                            "type": "string",
                            "description": "메일 수신 시작 날짜 (포함, receivedDateTime >= 이 값)"
                        },
                        "received_date_to": {
                            "type": "string",
                            "description": "메일 수신 종료 날짜 (포함, receivedDateTime <= 이 값)"
                        }
                    },
                    "required": [
                        "received_date_from",
                        "received_date_to"
                    ],
                    "baseModel": "FilterParams",
                    "targetParam": "filter_params"
                },
                "user_email": {
                    "type": "string",
                    "description": "이메일 주소를 입력하고 입력하지 않을 경우 내부에서 연결정보를 메일 주소를 추정함"
                }
            },
            "required": [
                "DatePeriodFilter"
            ]
        }
    },
    {
        "name": "mail_query_url",
        "description": "URL 방식 메일 조회 기능 - $filter 와 $select를 설정 가능",
        "inputSchema": {
            "type": "object",
            "properties": {
                "filter_params": {
                    "type": "object",
                    "description": "메일 필터링 조건",
                    "properties": {
                        "received_date_from": {
                            "type": "string",
                            "description": "메일 수신 시작 날짜"
                        },
                        "received_date_to": {
                            "type": "string",
                            "description": "메일 수신 종료 날짜"
                        }
                    },
                    "required": [],
                    "baseModel": "FilterParams",
                    "targetParam": "filter_params"
                },
                "select": {
                    "type": "object",
                    "description": "SelectParams parameters",
                    "properties": {
                        "body_preview": {
                            "type": "boolean",
                            "description": "메시지 본문의 처음 255자 (텍스트 형식)"
                        },
                        "created_date_time": {
                            "type": "boolean",
                            "description": "메시지 생성 날짜/시간 (ISO 8601 형식, UTC)"
                        },
                        "from_recipient": {
                            "type": "boolean",
                            "description": "메시지가 전송된 사서함의 소유자 (from 필드)"
                        },
                        "id": {
                            "type": "boolean",
                            "description": "메시지 고유 식별자 (읽기 전용)"
                        },
                        "received_date_time": {
                            "type": "boolean",
                            "description": "메시지 수신 날짜/시간 (ISO 8601 형식, UTC)"
                        }
                    },
                    "required": [],
                    "baseModel": "SelectParams",
                    "targetParam": "select_params"
                },
                "top": {
                    "type": "integer",
                    "description": "최대 결과 수"
                },
                "url": {
                    "type": "string",
                    "description": "only baseURL : https://graph.microsoft.com/v1.0/me/mailFolders/junkemail/messages?",
                    "targetParam": "url"
                },
                "user_email": {
                    "type": "string",
                    "description": "사용자 이메일 (인증용)"
                }
            },
            "required": [
                "url",
                "user_email"
            ]
        }
    },
    {
        "name": "mail_query_if_emaidID",
        "description": "email_id 가 조회된 경우 그걸 이용해서 메일을 조회한다. body를 제외한 내용이 조회된 경우 에이전트가 사용자의 의도를 분석하여 관련된 email_id를 호출한다.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "message_ids": {
                    "type": "string",
                    "description": "Auto-added parameter for message_ids"
                },
                "user_email": {
                    "type": "string",
                    "description": "이전 대화 내역에서 메일 주소를 찾아서 적용 없다면, 내부에서 자동으로 처리해 줄 거임"
                }
            },
            "required": [
                "message_ids"
            ]
        }
    }
]
""")




def get_tool_by_name(tool_name: str) -> Dict[str, Any] | None:
    """Get a specific tool definition by name"""
    for tool in MCP_TOOLS:
        if tool["name"] == tool_name:
            return tool
    return None


def get_tool_names() -> List[str]:
    """Get list of all available tool names"""
    return [tool["name"] for tool in MCP_TOOLS]
