"""
Server name mappings - AUTO-GENERATED FILE
DO NOT EDIT THIS FILE MANUALLY!

This file is automatically generated from @mcp_service decorators.
To regenerate: python ../jinja/generate_server_mappings.py
"""

# List of all known server names (from decorator values)
SERVER_NAMES = [
    "file_handler",
    "outlook",
]

# Default server name
DEFAULT_SERVER = "file_handler"


def get_server_name_from_profile(profile: str) -> str | None:
    """
    Determine server name from profile string

    Args:
        profile: Profile name or identifier

    Returns:
        Server name or None if not found
    """
    if profile == "_default":
        return DEFAULT_SERVER

    # Check if profile contains any known server name
    for server_name in SERVER_NAMES:
        if server_name in profile:
            return server_name

    return None


def get_server_name_from_path(path: str) -> str | None:
    """
    Determine server name from file path

    Args:
        path: File path to analyze

    Returns:
        Server name or None if not found
    """
    # Check each known server name
    for server_name in SERVER_NAMES:
        # Check for directory naming pattern (mcp_{server_name})
        if f"mcp_{server_name}" in path:
            return server_name
        # Also check for just server_name in path
        if server_name in path:
            return server_name

    return None
