"""
Server name mappings - AUTO-GENERATED FILE
DO NOT EDIT THIS FILE MANUALLY!

This file is automatically generated from @mcp_service decorators.
To regenerate: python ../jinja/generate_server_mappings.py
"""

# List of all known server names
SERVER_NAMES = [
    'mcp_file_handler',
    'mcp_outlook',
]

# Default server name
DEFAULT_SERVER = 'mcp_file_handler'


def get_server_name_from_profile(profile: str) -> str | None:
    """
    Determine server name from profile string

    Args:
        profile: Profile name or identifier

    Returns:
        Server name or None if not found
    """
    if profile == '_default':
        return DEFAULT_SERVER

    # Check if profile contains any known server name
    for server_name in SERVER_NAMES:
        if server_name in profile:
            return server_name

    return None


def get_server_name_from_path(path: str) -> str | None:
    """
    Determine server name from file path

    Args:
        path: File path to analyze

    Returns:
        Server name or None if not found
    """
    # Check each known server name
    for server_name in SERVER_NAMES:
        # Check for various naming patterns
        patterns = [
            f'mcp_{server_name}',
            f'{server_name}_mcp',
            f'mcp{server_name}',
        ]
        for pattern in patterns:
            if pattern in path:
                return server_name

    return None
