"""
Server name mappings - AUTO-GENERATED FILE
DO NOT EDIT THIS FILE MANUALLY!

This file is automatically generated from @mcp_service decorators.
To regenerate: python ../jinja/generate_server_mappings.py
"""
import os
import json

# List of all known server names (from decorator values)
SERVER_NAMES = [
    "file_handler",
    "outlook",
]

# Default server name
DEFAULT_SERVER = "file_handler"

# Cache for editor config
_editor_config_cache = None


def _load_editor_config():
    """Load editor_config.json and cache it"""
    global _editor_config_cache
    if _editor_config_cache is None:
        config_path = os.path.join(os.path.dirname(__file__), "editor_config.json")
        if os.path.exists(config_path):
            with open(config_path, "r", encoding="utf-8") as f:
                _editor_config_cache = json.load(f)
        else:
            _editor_config_cache = {}
    return _editor_config_cache


def get_server_name_from_profile(profile: str) -> str | None:
    """
    Determine server name from profile string

    Args:
        profile: Profile name or identifier

    Returns:
        Server name or None if not found
    """
    if profile == "_default":
        return DEFAULT_SERVER

    # Check editor_config for merged profiles
    config = _load_editor_config()
    if profile in config:
        profile_config = config[profile]
        # For merged profiles, return the profile name itself
        if profile_config.get("is_merged"):
            return profile
        # For derived profiles (is_reused), check base_profile
        if profile_config.get("is_reused") and profile_config.get("base_profile"):
            base = profile_config["base_profile"]
            if base in SERVER_NAMES:
                return base

    # Check if profile contains any known server name
    for server_name in SERVER_NAMES:
        if server_name in profile:
            return server_name

    # If profile exists in config, return profile name as server name
    if profile in config:
        return profile

    return None


def get_server_name_from_path(path: str) -> str | None:
    """
    Determine server name from file path

    Args:
        path: File path to analyze

    Returns:
        Server name or None if not found
    """
    # Check each known server name
    for server_name in SERVER_NAMES:
        # Check for directory naming pattern (mcp_{server_name})
        if f"mcp_{server_name}" in path:
            return server_name
        # Also check for just server_name in path
        if server_name in path:
            return server_name

    return None
